# Generated by Django 4.1.1 on 2022-09-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='SignUp',
        ),
    ]
