# Generated by Django 4.1.1 on 2022-09-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_signin_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
