# Generated by Django 4.1.2 on 2022-10-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
    ]
