# Generated by Django 4.1.2 on 2022-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_games_delete_banner_remove_game_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
