# Generated by Django 4.1.2 on 2022-10-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_games_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
