# Generated by Django 4.1.2 on 2022-10-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_category_alter_games_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
