# Generated by Django 4.1.2 on 2022-10-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_game_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='payment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
