# Generated by Django 4.1.2 on 2022-10-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_game_game_game_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='gamelink',
        ),
    ]
